language: python
python:
  - "3.6.4"

env: 
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings.production"
  - PYTHONPATH=$TRAVIS_BUILD_DIR/pur_beurre
  - DEPLOY_ENVIRON="PRODUCTION"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  -  python ./manage.py test product.tests.test_models
