language: python
python:
  - "3.6.4"

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test for Python versions 3.5 and below ...
