language: python
python:
  - "3.6.4"

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.production"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - export PYTHONPATH=/home/ubuntu/pur_beurre && py.test
